apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alloy-config
  namespace: grafana-alloy
data:
  config.alloy: |
      logging {
        level = "info"
        format = "logfmt"
      }

      prometheus.exporter.unix "node" { }
      
      prometheus.scrape "demo" {
        targets    = prometheus.exporter.unix.node.targets
        forward_to = [prometheus.remote_write.grafana_cloud.receiver]
      }
      
      prometheus.remote_write "grafana_cloud" {
        endpoint {
          url = "https://prometheus-prod-39-prod-eu-north-0.grafana.net/api/prom/push"
          basic_auth {
            username = env("GRAFANA_CLOUD_USERNAME")
            password = env("GRAFANA_CLOUD_PASSWORD")
          }
        }
      }

