---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-alloy
  namespace: grafana-alloy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-alloy
  template:
    metadata:
      labels:
        app: grafana-alloy
    spec:
      serviceAccountName: grafana-alloy
      containers:
        - name: grafana-alloy
          image: grafana/alloy:latest
          args:
            - run
            - /etc/alloy/config.alloy
          env:
            - name: GRAFANA_CLOUD_USERNAME
              valueFrom:
                secretKeyRef:
                  name: grafana-cloud-credentials
                  key: username
            - name: GRAFANA_CLOUD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-cloud-credentials
                  key: password
          volumeMounts:
            - name: config
              mountPath: /etc/alloy
              readOnly: true
            - name: root
              mountPath: /host
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: grafana-alloy-config
        - name: root
          hostPath:
            path: /

